name: MSBuild

on:
  push:
    branches: [ "v2","ci" ]
  pull_request:
    branches: [ "v2","ci" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install VCPKG packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vcpkg install cpp-httplib:x86-windows detours:x86-windows pystring:x86-windows nlohmann-json:x86-windows kubazip:x86-windows neargye-semver:x86-windows & vcpkg integrate install

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild .\BetterNCMII.sln -p:Platform="x86" -p:Configuration=Release
